################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
version: "2.1"

services:

  ###############################################################
  #    StateFun runtime
  ###############################################################

  statefun-manager:
    image: apache/flink-statefun:3.1.0-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      ROLE: master
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml

  statefun-worker:
    image: apache/flink-statefun:3.1.0-java11
    expose:
      - "6121"
      - "6122"
    environment:
      ROLE: worker
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml

  ###############################################################
  #    Kafka for ingress and egress
  ###############################################################

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ###############################################################
  # Forward a port 8000 from the host's machine
  ###############################################################
  
  host-machine:
    image: qoomon/docker-host@sha256:e0f021dd77c7c26d37b825ab2cbf73cd0a77ca993417da80a14192cb041937b0
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
    environment:
      PORTS: 8000

  ###############################################################
  #    Simple Kafka JSON producer to simulate ingress events
  ###############################################################

  producer:
    image: ververica/statefun-playground-producer:latest
    environment:
      APP_PATH: /mnt/input-example.json
      APP_KAFKA_HOST: kafka:9092
      APP_KAFKA_TOPIC: names
      APP_JSON_PATH: name
      APP_DELAY_SECONDS: 1
    volumes:
      - ./input-example.json:/mnt/input-example.json
